### ISSUE TITLE
Getting Error output.

### ISSUE THREAD

**Issue by mtwb47** [M1ndo/RichSpot#1]
When I run this after set up, I get:

`Error: [Errno 2] No such file or directory`

Repeated over and over again.

**Comment by SakuraBlossomTree** [comment]
Same Here

**Comment by M1ndo** [comment]
@mtwb47 @SakuraBlossomTree will push an update this evening, sorry for the delay.

**Comment by M1ndo** [comment]
Fixed, Please Update Richspot.
