### ISSUE TITLE
AUR package?

### ISSUE THREAD

**Issue by TheCheddarCheese** [M1ndo/RichSpot#4]
Since Arch is apparently externally managed and it isn't recommended to install packages through pip, I was wondering if there'a any AUR package in the works or planned?

**Comment by M1ndo** [comment]
@TheCheddarCheese for such a small tool i don't necessary think aur package would be necessary.

Instead just install it with pipx which is a lot better (i use arch as well).

**Comment by TheCheddarCheese** [comment]
> @TheCheddarCheese for such a small tool i don't necessary think aur package would be necessary.
> 
> Instead just install it with pipx which is a lot better (i use arch as well).

oh. i forgot that existed. lol
